# version: '3.9'

# services:
#   postgres:
#     image: postgres:16-alpine
#     container_name: bank_postgres
#     restart: always
#     environment:
#       POSTGRES_USER: bank_user
#       POSTGRES_PASSWORD: 123456
#       POSTGRES_DB: bank_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   #  NestJS API container
#   bank-server:
#     build:
#       context: ./bank-server
#       dockerfile: Dockerfile
#     container_name: bank_server
#     restart: always
#     depends_on:
#       - postgres
#     environment:
#       # Database configuration
#       DB_HOST: postgres
#       DB_PORT: 5432
#       DB_USERNAME: bank_user
#       DB_PASSWORD: 123456
#       DB_DATABASE: bank_db
#       PORT: 3000
#     ports:
#       - "4000:3000"
#     volumes:
#       - ./bank-server:/app
#       - /app/node_modules

# volumes:
#   postgres_data:

version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bank_postgres
    restart: always
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bank_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
